apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-tls
  namespace: observability
spec:
  secretName: kibana-tls
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  dnsNames:
    - kibana.test
