apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"otel-collector-gateway","namespace":"observability"},"spec":{"ports":[{"name":"otlp-grpc","port":4317,"targetPort":4317},{"name":"otlp-http","port":4318,"targetPort":4318}],"selector":{"app":"otel-collector-gateway"}}}
  creationTimestamp: "2026-04-07T23:32:21Z"
  name: otel-collector-gateway
  namespace: observability
  resourceVersion: "2222"
  uid: 47d443f4-3636-4c8d-9854-d218dc9c8070
spec:
  clusterIP: 10.43.29.56
  clusterIPs:
  - 10.43.29.56
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app: otel-collector-gateway
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
